"""Generate the SYNTHETIC demo fixture. Contains no radar observations.

Usage: roosttracker-demo [output_dir]
"""
from __future__ import annotations

import json
import math
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

from .manifest import validate_manifest

EVENT_ID = "kerr-lake-demo"
# Approximate Kerr Lake area, used only to place the synthetic picture on a map.
CENTER = (-78.35, 36.55)
BOUNDS = [-79.35, 35.9, -77.35, 37.2]
START = datetime(2026, 8, 12, 9, 30, tzinfo=timezone.utc)  # illustrative only
N_SCANS = 36
INTERVAL_MIN = 5
MISSING = {14, 15, 16, 25}  # simulated gaps


def _svg(i: int) -> str:
    r = 8 + i * 4.5
    op = max(0.05, 0.85 - i * 0.02)
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400" width="400" height="400">'
        '<rect width="400" height="400" fill="#0b1220"/>'
        f'<circle cx="200" cy="200" r="{r:.1f}" fill="none" stroke="#f5a623" '
        f'stroke-width="{6 + i * 0.2:.1f}" opacity="{op:.2f}"/>'
        f'<text x="8" y="392" fill="#ff6b6b" font-size="14" font-family="sans-serif">'
        "SYNTHETIC DEMO - not radar data</text></svg>"
    )


def build(out: Path) -> dict:
    ev_dir = out / EVENT_ID
    ev_dir.mkdir(parents=True, exist_ok=True)
    scans = []
    for i in range(N_SCANS):
        t = START + timedelta(minutes=INTERVAL_MIN * i)
        sid = f"demo-{i:03d}"
        s = {"id": sid, "time_utc": t.strftime("%Y-%m-%dT%H:%M:%SZ")}
        if i in MISSING:
            s["status"] = "missing"
        else:
            name = f"{sid}.svg"
            (ev_dir / name).write_text(_svg(i))
            s.update(status="available", asset=f"{EVENT_ID}/{name}",
                     source={"kind": "synthetic", "note": "generated by roosttracker.demo"},
                     fields=["synthetic"])
        scans.append(s)
    manifest = {
        "schema_version": "1",
        "synthetic": True,
        "event": {
            "id": EVENT_ID,
            "title": "SYNTHETIC DEMO - Kerr Lake dawn ring (not real data)",
            "radar_site": "KRAX",
            "verification": "synthetic",
            "notes": "Illustrative picture only. The real Aug 11-19, 2026 event has NOT been "
                     "verified in NOAA archive scans; inventory and coverage are still to be confirmed.",
        },
        "display": {"playback_fps": 15, "bounds": BOUNDS, "center": list(CENTER), "image_type": "svg"},
        "processing": {"name": "roosttracker.demo", "version": "0.1.0", "config": {"interval_min": INTERVAL_MIN}},
        "provenance": {"sources": [], "statement": "No external data used. Fully synthetic."},
        "scans": scans,
    }
    validate_manifest(manifest)
    (out / f"{EVENT_ID}.json").write_text(json.dumps(manifest, indent=2) + "\n")
    index = {"events": [{"id": EVENT_ID, "title": manifest["event"]["title"],
                         "synthetic": True, "manifest": f"{EVENT_ID}.json"}]}
    (out / "events.json").write_text(json.dumps(index, indent=2) + "\n")
    return manifest


def main(argv: list[str] | None = None) -> None:
    argv = sys.argv[1:] if argv is None else argv
    out = Path(argv[0]) if argv else Path("web/demo")
    build(out)
    print(f"Wrote synthetic demo fixture to {out}")


if __name__ == "__main__":
    main()
